name: ohotika
description: Охотика
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  path: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  hive_flutter: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_svg: ^2.0.5
  http: ^0.13.5
  url_launcher: ^6.1.14
  cached_network_image: ^3.3.0
  transparent_image: ^2.0.1
  share_plus: ^7.2.1
  flutter_html: ^3.0.0-beta.2
  sqflite: any
  path_provider: any
  provider: ^6.1.1
  email_validator: ^2.1.17
  image_picker: ^1.0.4
  carousel_slider: ^4.2.1
  zoom_widget: ^2.0.1
  intl: ^0.18.1
  flutter_multi_formatter: ^2.12.1
  onesignal_flutter: ^5.0.4
  appmetrica_plugin: ^1.4.0

flutter_launcher_icons:
  image_path: "assets/appicon.jpg"
  android: true
  ios: true
  remove_alpha_ios: true
  android_12:
    image_path: "assets/appicon.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf
    - family: DaysSansBlack
      fonts:
        - asset: assets/fonts/days_sans_black.otf